### ISSUE TITLE
Phantoms not Hostile

### ISSUE THREAD

**Issue by VoidFairy** [finallion/The-Graveyard-FORGE-#49]
### What's the issue you encountered?

With your mod installed phantoms aren't hostile, even when attacked. They only run away. Unable to farm them for membranes as they won't target the player. 

### How can the issue be reproduced?

I tested this by removing mods except yours. I used "/summon phantom" before putting in your mod and it was hostile and attacking me. After dropping in the mod and rebooting the game it attacks once but then immediately runs away and never attacks. I'm using 1.18.2, forge version 40.1.69. 
Mod version 1.9.1_(FORGE)_for_1.18.2.

I hope this is the right area to report this I'm not really any good at this stuff and I'm not sure what other information you might need so please excuse me for not knowing.

**Comment by finallion** [comment]
Hey! I tried to reproduce this issue but with no success. Does this happen with spawn eggs as well and even right below the phantoms? You can send me a recording of this and with onyl the Graveyard present so I can understand what is happening, if you like. My discord is Finallion#3197 :)

**Comment by finallion** [comment]
Another thought, do have cats in your vicinity? They scare phantoms.

**Comment by EvilFlyingJester** [comment]
https://drive.google.com/file/d/1F51TEjQpwCHBCuOyrLGzBlkRPkUSCP3e/view?usp=sharing

This video shows the Phantom issue your mod is giving my games. Please excuse the NOOBness (I couldn't remember the original github account I made to comment & my video editing skills are 0, it I'm not good at this stuff.) I did make sure to include in the video that when I turn your mod off I am immediately dive-bombed to death by phantoms, but with your mod in the only seem to attack when I am close, and otherwise do not seem to target me (very much, you can see they do a little?) but it's no where near what they do without.

**Comment by EvilFlyingJester** [comment]
Here is another video I took showing how they don't work with a phantom farm. The start of the video I turn off your mod and show the farm works. Then I turn on your mod and the phantoms only circle over head, never diving at me. When I turn your mods off the farm immediately begins working again.  No cats have been around in these test worlds or in my own played worlds when the phantom farms are not working. With your mod in the phantoms do seem to attack occasionally, usually only if I get too close, and even then they do not really stay on me as if they are targeting me? 

https://youtu.be/Mlfhq7vcjlo

**Comment by finallion** [comment]
Thank you so much and all the effort you took. I checked my whole mod and nothing indicates any interference with the phantom, any super classes or the player. Phantom is not even mentioned once in the mod. I'm trying to reproduce the error with the help of your videos and let you know!

**Comment by finallion** [comment]
I found the issues and released a new version (1.9.2), thanks again!
