### ISSUE TITLE
[Question][1.16.5] How many book is there?

### ISSUE THREAD

**Issue by drakray** [finallion/The-Graveyard-FORGE-#8]
Simple question, as I am kind of a collector/hoarder XD
I don't really want spoiler of location, just a number.
I found out that some structure have them, always the same book in the same spot.
Might be a nice touch to randomize emplacement, if possible at all(probably via slight variant of the same building I suppose)

Thank you for your good work :D , I hope you continue to support 1.16.5 despite 1.18 lol

**Comment by drakray** [comment]
Also, the books authors are "PlayerXYZ"(random dev player handle), could be nice to "name" the story protagonist

**Comment by finallion** [comment]
Hey! There are currently about 6 books, but more to come. To only change the spot of the book would mean to have the same structure file over and over with only minimal change - but this mod is still in its beginning and more structures will be added so that they wont double as much. And each structure will have a specific part in the "story".
For the protagonist: thats a neat idea. I'm looking into it :)
